### ISSUE TITLE
[Bug] Getting an error related to colorlog during the training

### ISSUE THREAD

**Issue by abirkorched** [graviraja/MLOps-Basics#10]
## 🐛 Bug

I get an error ​ ​when trying to train the model using the code from week2.

##### Stack trace

`Could not load override hydra/job_logging/colorlog`

##### Environment

I created a virtual environment using week2 requirements.

**Comment by graviraja** [comment]
Hi @abirkorched 
Can you try installing the following versions and check
```
pip install hydra-core==1.1.0
pip install hydra-colorlog==1.1.0
```

**Comment by abirkorched** [comment]
Hi @graviraja, 

I tested with version 1.1.0. It works fine now :) 

Thank you!
