### ISSUE TITLE
Different module metrics for train/val

### ISSUE THREAD

**Issue by rohitgr7** [graviraja/MLOps-Basics#16]
Module metrics stores internal states computed over each call on different batches. So using the same instance for both train and val might not lead to correct results when computed over epoch with (on_epoch=True) in step hooks. I'd suggest creating separate ones for each task (train & val).

ref: https://torchmetrics.readthedocs.io/en/latest/pages/quickstart.html#module-metrics

https://github.com/graviraja/MLOps-Basics/blob/d4ad5a9045dc9fe5edbb4bf461d0aaf1338eb5b6/week_9_monitoring/model.py#L24-L33

**Comment by rohitgr7** [comment]
cc @graviraja

**Comment by graviraja** [comment]
@rohitgr7 fixed it. Thanks for pointing it out :)
