### ISSUE TITLE
Potential Error in Blog of Week 0

### ISSUE THREAD

**Issue by VirajBagal** [graviraja/MLOps-Basics#19]
Hey Raviraj, great work. I am learning a lot. 

In the week 0 blog post, you mentioned the following: 
`
As an example, I will be implementing EarlyStopping callback. This helps the model not to overfit by mointoring on a certain parameter (val_loss in this case) The best model will be saved in the dirpath.
`

But in the code, you have used `ModelCheckpoint` callback and did not use `EarlyStopping`. I believe `EarlyStopping` and `ModelCheckpoint` callbacks are two completely different callbacks. Please correct if I am wrong. Thanks.

**Comment by graviraja** [comment]
Hi @VirajBagal , thanks for pointing it out. You are correct it is ModelCheckpoint callback, not an EarlyStopping callback. Fixed it. Please check it out now.
