### ISSUE TITLE
Malformed URLs

### ISSUE THREAD

**Issue by Sushant5776** [graviraja/MLOps-Basics#38]
No link to the blog post is active. I think the entire website is down.

**Comment by zhifanl** [comment]
same

**Comment by hkristof03** [comment]
same

**Comment by SandeepaDevin** [comment]
It's still down.

**Comment by colinhuliselan** [comment]
I believe the corresponding posts can be found here: https://deep-learning-blogs.vercel.app/blog.

**Comment by graviraja** [comment]
Have some dns issue. For now, updated the readme with alternative blog URLs.
